Improved arg support.

diff --git a/nde b/nde
--- a/nde
+++ b/nde
@@ -36,11 +36,9 @@ for(let i=30; i>0; i--) {
 version=$(docker run -v $(pwd):/code:delegated node:$latest_node_version node -e "$version_check")
 
 NODE_VERSION=10
-POSITIONAL=()
 ARGS=()
 # Extract the first port so we can add a env variable
 PORTS=()
-GOT_POSITIONAL=0
 while [[ $# -gt 0 ]]
 do
   key="$1"
@@ -51,47 +49,43 @@ do
     NEXT_OPT_ARG=1
   fi
 
-  if [ $GOT_POSITIONAL -gt 0 ]; then
-    POSITIONAL+=("$1") # save it in an array for later
-    shift
-  else
-    case $key in
-      --node)
-        if [ $NEXT_OPT_ARG -eq 1 ]; then
-          >&2 echo "Invalid node version $2"
-          exit 2
-        else
-          version="$2"
-          shift
-          shift
-        fi
-        ;;
-      -p|--port|--expose)
-        PORTS+=("$2")
+  case $key in
+    --node)
+      if [ $NEXT_OPT_ARG -eq 1 ]; then
+        >&2 echo "Invalid node version $2"
+        exit 2
+      else
+        version="$2"
+        shift
+        shift
+      fi
+      ;;
+    -p|--port|--expose)
+      echo "port $1 $2"
+      PORTS+=("$2")
+      ARGS+=("$1 $2")
+      shift
+      shift
+      ;;
+    -*=*|--*=*)
+      ARGS+=("$1")
+      shift
+      ;;
+    -*|--*)
+      if [ $NEXT_OPT_ARG ]; then
         ARGS+=("$1 $2")
         shift
-        ;;
-      -*=*|--*=*)
+        shift
+      else
         ARGS+=("$1")
         shift
-        ;;
-      -*|--*)
-        if [ $NEXT_OPT_ARG ]; then
-          ARGS+=("$1 $2")
-          shift
-          shift
-        else
-          ARGS+=("$1")
-          shift
-        fi
-        ;;
-      *)    # unknown option
-        GOT_POSITIONAL=1
-        POSITIONAL+=("$1") # save it in an array for later
-        shift
-        ;;
-    esac
-  fi
+      fi
+      ;;
+    *)    # unknown option
+      # Exit loop leaving remaining args on $@ intact
+      break
+      ;;
+  esac
 
 done
 
@@ -118,17 +112,12 @@ fi
 
 >&2 echo "node:$version"
 
-if [ ${#POSITIONAL[@]} -lt 1 ]; then
-  COMMAND="bash"
-else
-  COMMAND="${POSITIONAL[@]}"
-fi
-
 docker run \
   -i \
   -t \
+  --workdir /code \
   -v $(pwd):/code:delegated \
   -e PORT=$PORT \
-  "${ARGS[@]}" \
-  node:$version bash -c "cd /code && $COMMAND"
+  ${ARGS[@]} \
+  node:$version "${@:-bash}"
 
